[2025-05-06T09:21:06.915+0000] {processor.py:186} INFO - Started process (PID=113) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_dataset_alias.py
[2025-05-06T09:21:06.917+0000] {processor.py:914} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_dataset_alias.py for tasks to queue
[2025-05-06T09:21:06.921+0000] {logging_mixin.py:190} INFO - [2025-05-06T09:21:06.920+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_dataset_alias.py
[2025-05-06T09:21:15.222+0000] {logging_mixin.py:190} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7fc15a3cd260>
[2025-05-06T09:21:15.224+0000] {logging_mixin.py:190} WARNING - Traceback (most recent call last):
[2025-05-06T09:21:15.226+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/weakref.py", line 369, in remove
[2025-05-06T09:21:15.229+0000] {logging_mixin.py:190} WARNING -     def remove(k, selfref=ref(self)):
[2025-05-06T09:21:15.230+0000] {logging_mixin.py:190} WARNING -   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/manager.py", line 466, in _exit_gracefully
[2025-05-06T09:21:15.232+0000] {logging_mixin.py:190} WARNING -     self.log.debug("Current Stacktrace is: %s", "\n".join(map(str, inspect.stack())))
[2025-05-06T09:21:15.234+0000] {logging_mixin.py:190} WARNING -                                                                    ^^^^^^^^^^^^^^^
[2025-05-06T09:21:15.236+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 1781, in stack
[2025-05-06T09:21:15.240+0000] {logging_mixin.py:190} WARNING -     return getouterframes(sys._getframe(1), context)
[2025-05-06T09:21:15.242+0000] {logging_mixin.py:190} WARNING -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-06T09:21:15.244+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 1756, in getouterframes
[2025-05-06T09:21:15.248+0000] {logging_mixin.py:190} WARNING -     traceback_info = getframeinfo(frame, context)
[2025-05-06T09:21:15.250+0000] {logging_mixin.py:190} WARNING -                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-06T09:21:15.251+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 1718, in getframeinfo
[2025-05-06T09:21:15.255+0000] {logging_mixin.py:190} WARNING -     lines, lnum = findsource(frame)
[2025-05-06T09:21:15.257+0000] {logging_mixin.py:190} WARNING -                   ^^^^^^^^^^^^^^^^^
[2025-05-06T09:21:15.259+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 1090, in findsource
[2025-05-06T09:21:15.263+0000] {logging_mixin.py:190} WARNING -     module = getmodule(object, file)
[2025-05-06T09:21:15.265+0000] {logging_mixin.py:190} WARNING -              ^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-06T09:21:15.267+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 1013, in getmodule
[2025-05-06T09:21:15.271+0000] {logging_mixin.py:190} WARNING -     f = getabsfile(module)
[2025-05-06T09:21:15.273+0000] {logging_mixin.py:190} WARNING -         ^^^^^^^^^^^^^^^^^^
[2025-05-06T09:21:15.275+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 982, in getabsfile
[2025-05-06T09:21:15.279+0000] {logging_mixin.py:190} WARNING -     _filename = getsourcefile(object) or getfile(object)
[2025-05-06T09:21:15.281+0000] {logging_mixin.py:190} WARNING -                 ^^^^^^^^^^^^^^^^^^^^^
[2025-05-06T09:21:15.283+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 958, in getsourcefile
[2025-05-06T09:21:15.286+0000] {logging_mixin.py:190} WARNING -     if any(filename.endswith(s) for s in all_bytecode_suffixes):
[2025-05-06T09:21:15.289+0000] {logging_mixin.py:190} WARNING -        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-06T09:21:15.291+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 958, in <genexpr>
[2025-05-06T09:21:15.295+0000] {logging_mixin.py:190} WARNING -     if any(filename.endswith(s) for s in all_bytecode_suffixes):
[2025-05-06T09:21:15.297+0000] {logging_mixin.py:190} WARNING -            ^^^^^^^^^^^^^^^^^^^^
[2025-05-06T09:21:15.299+0000] {logging_mixin.py:190} WARNING -   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/manager.py", line 470, in _exit_gracefully
[2025-05-06T09:21:15.302+0000] {logging_mixin.py:190} WARNING -     sys.exit(os.EX_OK)
[2025-05-06T09:21:15.304+0000] {logging_mixin.py:190} WARNING - SystemExit: 0
[2025-05-06T09:21:15.635+0000] {processor.py:925} INFO - DAG(s) 'dataset_s3_bucket_producer', 'dataset_s3_bucket_consumer', 'dataset_alias_example_alias_producer', 'dataset_alias_example_alias_consumer' retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_dataset_alias.py
[2025-05-06T09:21:15.744+0000] {logging_mixin.py:190} INFO - [2025-05-06T09:21:15.743+0000] {dag.py:3239} INFO - Sync 4 DAGs
[2025-05-06T09:21:15.794+0000] {logging_mixin.py:190} INFO - [2025-05-06T09:21:15.794+0000] {dag.py:4180} INFO - Setting next_dagrun for dataset_alias_example_alias_consumer to None, run_after=None
[2025-05-06T09:21:15.799+0000] {logging_mixin.py:190} INFO - [2025-05-06T09:21:15.799+0000] {dag.py:4180} INFO - Setting next_dagrun for dataset_alias_example_alias_producer to None, run_after=None
[2025-05-06T09:21:15.802+0000] {logging_mixin.py:190} INFO - [2025-05-06T09:21:15.802+0000] {dag.py:4180} INFO - Setting next_dagrun for dataset_s3_bucket_consumer to None, run_after=None
[2025-05-06T09:21:15.804+0000] {logging_mixin.py:190} INFO - [2025-05-06T09:21:15.804+0000] {dag.py:4180} INFO - Setting next_dagrun for dataset_s3_bucket_producer to None, run_after=None
[2025-05-06T09:21:15.839+0000] {processor.py:208} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_dataset_alias.py took 8.931 seconds
